-- MySQL Script generated by MySQL Workbench
-- Do 20 Mai 2021 15:37:54 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lectureplan
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `lectureplan` ;

-- -----------------------------------------------------
-- Schema lectureplan
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lectureplan` ;
USE `lectureplan` ;

-- -----------------------------------------------------
-- Table `lectureplan`.`userRights`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lectureplan`.`userRights` ;

CREATE TABLE IF NOT EXISTS `lectureplan`.`userRights` (
  `samlUID` INT UNSIGNED NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `isAdmin` TINYINT(1) NOT NULL,
  `addCourse` TINYINT(1) NOT NULL,
  `editEvent` TINYINT(1) NOT NULL,
  `addEvent` TINYINT(1) NOT NULL,
  PRIMARY KEY (`samlUID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lectureplan`.`lecturers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lectureplan`.`lecturers` ;

CREATE TABLE IF NOT EXISTS `lectureplan`.`lecturers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `surname` VARCHAR(255) NOT NULL,
  `givenName` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `samlUID` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lecturers_userRights1_idx` (`samlUID` ASC) VISIBLE,
  CONSTRAINT `fk_lecturers_userRights1`
    FOREIGN KEY (`samlUID`)
    REFERENCES `lectureplan`.`userRights` (`samlUID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lectureplan`.`semesters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lectureplan`.`semesters` ;

CREATE TABLE IF NOT EXISTS `lectureplan`.`semesters` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `start` DATE NOT NULL,
  `end` DATE NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lectureplan`.`courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lectureplan`.`courses` ;

CREATE TABLE IF NOT EXISTS `lectureplan`.`courses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `name` VARCHAR(255) NOT NULL,
  `year` YEAR(4) NOT NULL,
  `faculty` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lectureplan`.`lectures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lectureplan`.`lectures` ;

CREATE TABLE IF NOT EXISTS `lectureplan`.`lectures` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `name` VARCHAR(255) NOT NULL,
  `lecturer` INT NOT NULL,
  `semester` INT NOT NULL,
  `course` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lecture_lecturer_idx` (`lecturer` ASC) VISIBLE,
  INDEX `fk_lectures_semester1_idx` (`semester` ASC) VISIBLE,
  INDEX `fk_lectures_courses1_idx` (`course` ASC) VISIBLE,
  CONSTRAINT `fk_lecture_lecturer`
    FOREIGN KEY (`lecturer`)
    REFERENCES `lectureplan`.`lecturers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lectures_semester1`
    FOREIGN KEY (`semester`)
    REFERENCES `lectureplan`.`semesters` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lectures_courses1`
    FOREIGN KEY (`course`)
    REFERENCES `lectureplan`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lectureplan`.`events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lectureplan`.`events` ;

CREATE TABLE IF NOT EXISTS `lectureplan`.`events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lecture` INT NOT NULL,
  `date` DATE NOT NULL,
  `startTime` TIME NOT NULL,
  `endTime` TIME NOT NULL,
  `room` VARCHAR(255) NOT NULL,
  `confirmed` TINYINT(1) NOT NULL,
  `comment` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_events_lecture1_idx` (`lecture` ASC) VISIBLE,
  CONSTRAINT `fk_events_lecture1`
    FOREIGN KEY (`lecture`)
    REFERENCES `lectureplan`.`lectures` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lectureplan`.`unavailableTimes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lectureplan`.`unavailableTimes` ;

CREATE TABLE IF NOT EXISTS `lectureplan`.`unavailableTimes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `startTime` DATETIME NOT NULL,
  `endTime` DATETIME NOT NULL,
  `lecturer` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk__lecturers1_idx` (`lecturer` ASC) VISIBLE,
  CONSTRAINT `fk__lecturers1`
    FOREIGN KEY (`lecturer`)
    REFERENCES `lectureplan`.`lecturers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lectureplan`.`preferredWeekdays`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lectureplan`.`preferredWeekdays` ;

CREATE TABLE IF NOT EXISTS `lectureplan`.`preferredWeekdays` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lecturer` INT NOT NULL,
  `monday` TINYINT(1) NOT NULL,
  `tuesday` TINYINT(1) NOT NULL,
  `wednesday` TINYINT(1) NOT NULL,
  `thursday` TINYINT(1) NOT NULL,
  `friday` TINYINT(1) NOT NULL,
  `saturday` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`, `lecturer`),
  INDEX `fk_preferredWeekdays_lecturers1_idx` (`lecturer` ASC) VISIBLE,
  CONSTRAINT `fk_preferredWeekdays_lecturers1`
    FOREIGN KEY (`lecturer`)
    REFERENCES `lectureplan`.`lecturers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lectureplan`.`preferredDays`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lectureplan`.`preferredDays` ;

CREATE TABLE IF NOT EXISTS `lectureplan`.`preferredDays` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `day` DATE NOT NULL,
  `lecturer` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk__lecturers1_idx` (`lecturer` ASC) VISIBLE,
  CONSTRAINT `fk__lecturers10`
    FOREIGN KEY (`lecturer`)
    REFERENCES `lectureplan`.`lecturers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lectureplan`.`courseSemesters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lectureplan`.`courseSemesters` ;

CREATE TABLE IF NOT EXISTS `lectureplan`.`courseSemesters` (
  `idCourse` INT NOT NULL,
  `idSemester` INT NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idCourse`, `idSemester`),
  UNIQUE INDEX `UQ` (`idCourse` ASC, `idSemester` ASC) VISIBLE,
  INDEX `fk_courseSemesters_semesters1_idx` (`idSemester` ASC) VISIBLE,
  CONSTRAINT `fk_courseSemesters_courses1`
    FOREIGN KEY (`idCourse`)
    REFERENCES `lectureplan`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_courseSemesters_semesters1`
    FOREIGN KEY (`idSemester`)
    REFERENCES `lectureplan`.`semesters` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `lectureplan` ;

-- -----------------------------------------------------
-- Placeholder table for view `lectureplan`.`eventView`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lectureplan`.`eventView` (`id` INT, `name` INT, `surname` INT, `date` INT, `startTime` INT, `endTime` INT, `room` INT, `confirmed` INT);

-- -----------------------------------------------------
-- View `lectureplan`.`eventView`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lectureplan`.`eventView`;
DROP VIEW IF EXISTS `lectureplan`.`eventView` ;
USE `lectureplan`;
CREATE  OR REPLACE VIEW `eventView` AS
    SELECT 
        events.id,
        courses.name,
        lecturers.surname,
        events.date,
        events.startTime,
        events.endTime,
        events.room,
        events.confirmed
    FROM
        events,
        courses,
        lectures,
        lecturers
    WHERE
        events.course = courses.id
            AND events.lecture = lectures.id
            AND lecture.lecturer = lecturers.id;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
