-- MySQL Script generated by MySQL Workbench
-- Mi 19 Mai 2021 14:35:19 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lectureplan
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `lectureplan` ;

-- -----------------------------------------------------
-- Schema lectureplan
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lectureplan` ;
USE `lectureplan` ;

-- -----------------------------------------------------
-- Table `lectureplan`.`userRights`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lectureplan`.`userRights` ;

CREATE TABLE IF NOT EXISTS `lectureplan`.`userRights` (
  `samlUID` INT UNSIGNED NOT NULL,
  `email` VARCHAR(255) NULL,
  `isAdmin` TINYINT(1) NOT NULL,
  `addCourse` TINYINT(1) NOT NULL,
  `editEvent` TINYINT(1) NOT NULL,
  `addEvent` TINYINT(1) NOT NULL,
  PRIMARY KEY (`samlUID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lectureplan`.`lecturers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lectureplan`.`lecturers` ;

CREATE TABLE IF NOT EXISTS `lectureplan`.`lecturers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `surname` VARCHAR(255) NULL,
  `givenName` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `samlUID` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lecturers_userRights1_idx` (`samlUID` ASC) VISIBLE,
  CONSTRAINT `fk_lecturers_userRights1`
    FOREIGN KEY (`samlUID`)
    REFERENCES `lectureplan`.`userRights` (`samlUID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lectureplan`.`lectures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lectureplan`.`lectures` ;

CREATE TABLE IF NOT EXISTS `lectureplan`.`lectures` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `name` VARCHAR(255) NULL,
  `lecturer` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lecture_lecturer_idx` (`lecturer` ASC) VISIBLE,
  CONSTRAINT `fk_lecture_lecturer`
    FOREIGN KEY (`lecturer`)
    REFERENCES `lectureplan`.`lecturers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lectureplan`.`courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lectureplan`.`courses` ;

CREATE TABLE IF NOT EXISTS `lectureplan`.`courses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `field` VARCHAR(255) NULL,
  `year` YEAR(4) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lectureplan`.`events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lectureplan`.`events` ;

CREATE TABLE IF NOT EXISTS `lectureplan`.`events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lecture` INT NOT NULL,
  `course` INT NOT NULL,
  `date` DATE NOT NULL,
  `startTime` TIME NOT NULL,
  `endTime` TIME NOT NULL,
  `confirmed` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_events_lecture1_idx` (`lecture` ASC) VISIBLE,
  INDEX `fk_events_courses1_idx` (`course` ASC) VISIBLE,
  CONSTRAINT `fk_events_lecture1`
    FOREIGN KEY (`lecture`)
    REFERENCES `lectureplan`.`lectures` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_courses1`
    FOREIGN KEY (`course`)
    REFERENCES `lectureplan`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `lectureplan` ;

-- -----------------------------------------------------
-- Placeholder table for view `lectureplan`.`eventView`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lectureplan`.`eventView` (`id` INT, `field` INT, `year` INT, `surname` INT, `date` INT, `startTime` INT, `endTime` INT, `confirmed` INT);

-- -----------------------------------------------------
-- View `lectureplan`.`eventView`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lectureplan`.`eventView`;
DROP VIEW IF EXISTS `lectureplan`.`eventView` ;
USE `lectureplan`;
CREATE  OR REPLACE VIEW `eventView` AS
    SELECT 
        events.id,
        course.field,
        course.year,
        lecturers.surname,
        events.date,
        events.startTime,
        events.endTime,
        events.confirmed
    FROM
        events,
        courses,
        lectures,
        lecturers
    WHERE
        events.course = course.id
            AND events.lecture = lecture.id
            AND lecture.lecturer = lecturers.id;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
